version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"         # If dependencies are in root
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/client"   # If you have frontend in /client folder
    schedule:
      interval: "weekly"
