
name: Metrics
on:
  schedule: [{ cron: "0 * * * *" }] # every hour
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@latest
        with:
          # Required
          token: ${{ secrets.METRICS_TOKEN }}

          # Options (choose as needed)
          user: shubham-cyber-prog
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
